import Head from 'next/head'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta property="twitter:title" content="Sachit Kurup"></meta>
        <meta property="twitter:image" content="./images/hero-image.jpeg"></meta>
        <meta property="twitter:card" content="/images/hero-image.jpeg"></meta>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}